#!/usr/bin/perl -w

print "# generated by usys.pl - do not edit\n";
print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $prefix = "sys_";
    my $name = shift;
    if ($name eq "sbrk") {
        print ".global $prefix$name\n";
        print "$prefix$name:\n";
    } else {
        print ".global $name\n";
        print "$name:\n";
    }
    print " li a7, SYS_$name\n";
    print " ecall\n";
    print " ret\n";
}

entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("write");
entry("read");
entry("close");
entry("kill");
entry("exec");
entry("fstat");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("open");
entry("mknod");
entry("unlink");
entry("link");
entry("mkdir");
entry("isatty");
entry("getnumchild");
entry("getpid2");
entry("getppid");
entry("hello");
entry("pause");
entry("getsyscount");
entry("getchildsyscount");
entry("getlevel");
entry("getmlfqinfo");
entry("getvmstats");
entry("setdisksched");
entry("setraidmode");entry("faildisk");
entry("recovereddisk");
